#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserArrowButton

#include "Basic.hpp"

#include "ActivityBrowserArrowButton_classes.hpp"
#include "ActivityBrowserArrowButton_parameters.hpp"


namespace SDK
{

// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.UpdateArrowColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              HoverColor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::UpdateArrowColor(const struct FLinearColor& Color, const struct FLinearColor& HoverColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "UpdateArrowColor");

	Params::ActivityBrowserArrowButton_C_UpdateArrowColor Parms{};

	Parms.Color = std::move(Color);
	Parms.HoverColor = std::move(HoverColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.SnapAnimationToEnd
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 InAnimation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::SnapAnimationToEnd(class UWidgetAnimation* InAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "SnapAnimationToEnd");

	Params::ActivityBrowserArrowButton_C_SnapAnimationToEnd Parms{};

	Parms.InAnimation = InAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "PreConstruct");

	Params::ActivityBrowserArrowButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.OnRowReset
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::OnRowReset(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "OnRowReset");

	Params::ActivityBrowserArrowButton_C_OnRowReset Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.OnRowActiveChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::OnRowActiveChanged(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "OnRowActiveChanged");

	Params::ActivityBrowserArrowButton_C_OnRowActiveChanged Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.GetActiveAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidgetAnimation**                ActiveAnimation                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::GetActiveAnimation(class UWidgetAnimation** ActiveAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "GetActiveAnimation");

	Params::ActivityBrowserArrowButton_C_GetActiveAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ActiveAnimation != nullptr)
		*ActiveAnimation = Parms.ActiveAnimation;
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.ExecuteUbergraph_ActivityBrowserArrowButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserArrowButton_C::ExecuteUbergraph_ActivityBrowserArrowButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "ExecuteUbergraph_ActivityBrowserArrowButton");

	Params::ActivityBrowserArrowButton_C_ExecuteUbergraph_ActivityBrowserArrowButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserArrowButton_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserArrowButton.ActivityBrowserArrowButton_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserArrowButton_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserArrowButton_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}

}

