#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserTileDetailsDisplay

#include "Basic.hpp"

#include "ActivityBrowserTileDetailsDisplay_classes.hpp"
#include "ActivityBrowserTileDetailsDisplay_parameters.hpp"


namespace SDK
{

// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.SnapToEndOfAnimation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 InAnimation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EUMGSequencePlayMode                    PlayMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::SnapToEndOfAnimation(class UWidgetAnimation* InAnimation, EUMGSequencePlayMode PlayMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "SnapToEndOfAnimation");

	Params::ActivityBrowserTileDetailsDisplay_C_SnapToEndOfAnimation Parms{};

	Parms.InAnimation = InAnimation;
	Parms.PlayMode = PlayMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.SetFavoriteButtonAvailable
// (Public, BlueprintCallable, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::SetFavoriteButtonAvailable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "SetFavoriteButtonAvailable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.SetEpicActivityStyling
// (Public, BlueprintCallable, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::SetEpicActivityStyling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "SetEpicActivityStyling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.SetDetailsButtonAvailable
// (Public, BlueprintCallable, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::SetDetailsButtonAvailable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "SetDetailsButtonAvailable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.RefreshDisabledState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::RefreshDisabledState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "RefreshDisabledState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnTileActiveSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsTileActive                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::OnTileActiveSet(const bool bIsTileActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnTileActiveSet");

	Params::ActivityBrowserTileDetailsDisplay_C_OnTileActiveSet Parms{};

	Parms.bIsTileActive = bIsTileActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnSocialUsersPlayingChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NumPlaying                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::OnSocialUsersPlayingChanged(int32 NumPlaying)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnSocialUsersPlayingChanged");

	Params::ActivityBrowserTileDetailsDisplay_C_OnSocialUsersPlayingChanged Parms{};

	Parms.NumPlaying = NumPlaying;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnPreviewImageChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsLoading                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UTexture*                   Texture                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::OnPreviewImageChanged(const bool bIsLoading, const class UTexture* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnPreviewImageChanged");

	Params::ActivityBrowserTileDetailsDisplay_C_OnPreviewImageChanged Parms{};

	Parms.bIsLoading = bIsLoading;
	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnPartySizeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             PartySize                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::OnPartySizeChanged(const int32 PartySize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnPartySizeChanged");

	Params::ActivityBrowserTileDetailsDisplay_C_OnPartySizeChanged Parms{};

	Parms.PartySize = PartySize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnLocalPlayerPromotedToLeader
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::OnLocalPlayerPromotedToLeader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnLocalPlayerPromotedToLeader");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnLocalPlayerDemoted
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::OnLocalPlayerDemoted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnLocalPlayerDemoted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnIsFavoriteChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsFavorite                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::OnIsFavoriteChanged(const bool bIsFavorite)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnIsFavoriteChanged");

	Params::ActivityBrowserTileDetailsDisplay_C_OnIsFavoriteChanged Parms{};

	Parms.bIsFavorite = bIsFavorite;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.OnDetailsUpdated
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::OnDetailsUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "OnDetailsUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.HandleInputMethodChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::HandleInputMethodChanged(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "HandleInputMethodChanged");

	Params::ActivityBrowserTileDetailsDisplay_C_HandleInputMethodChanged Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.ExecuteUbergraph_ActivityBrowserTileDetailsDisplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTileDetailsDisplay_C::ExecuteUbergraph_ActivityBrowserTileDetailsDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "ExecuteUbergraph_ActivityBrowserTileDetailsDisplay");

	Params::ActivityBrowserTileDetailsDisplay_C_ExecuteUbergraph_ActivityBrowserTileDetailsDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.DisableClickTimerExpired
// (BlueprintCallable, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::DisableClickTimerExpired()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "DisableClickTimerExpired");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTileDetailsDisplay.ActivityBrowserTileDetailsDisplay_C.BP_OnClicked
// (Event, Protected, BlueprintEvent)

void UActivityBrowserTileDetailsDisplay_C::BP_OnClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTileDetailsDisplay_C", "BP_OnClicked");

	UObject::ProcessEvent(Func, nullptr);
}

}

