#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityPlayerBrowserTile

#include "Basic.hpp"

#include "DiscoveryBrowserUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivityPlayerBrowserTile.ActivityPlayerBrowserTile_C
// 0x0000 (0x0340 - 0x0340)
class UActivityPlayerBrowserTile_C final : public UFortActivityPlayerBrowserTile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ActivityPlayerBrowserTile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActivityPlayerBrowserTile_C")
	}
	static class UActivityPlayerBrowserTile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivityPlayerBrowserTile_C>();
	}
};
DUMPER7_ASSERTS_UActivityPlayerBrowserTile_C;

}

