#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityDetailsDisplay

#include "Basic.hpp"

#include "ActivityDetailsDisplay_classes.hpp"
#include "ActivityDetailsDisplay_parameters.hpp"


namespace SDK
{

// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.UpdateVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ShowWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::UpdateVisibility(class UWidget* Target, bool ShowWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "UpdateVisibility");

	Params::ActivityDetailsDisplay_C_UpdateVisibility Parms{};

	Parms.Target = Target;
	Parms.ShowWidget = ShowWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.UpdateFavoriteStatus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFavorite                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PlayAnimation_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::UpdateFavoriteStatus(bool IsFavorite, bool PlayAnimation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "UpdateFavoriteStatus");

	Params::ActivityDetailsDisplay_C_UpdateFavoriteStatus Parms{};

	Parms.IsFavorite = IsFavorite;
	Parms.PlayAnimation_0 = PlayAnimation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.UpdateDetailVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UActivityDetailsDisplay_C::UpdateDetailVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "UpdateDetailVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.UpdateButtonVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ShowWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::UpdateButtonVisibility(class UWidget* Target, bool ShowWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "UpdateButtonVisibility");

	Params::ActivityDetailsDisplay_C_UpdateButtonVisibility Parms{};

	Parms.Target = Target;
	Parms.ShowWidget = ShowWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.SetButtonsInteractable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInteractionEnabled                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::SetButtonsInteractable(bool IsInteractionEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "SetButtonsInteractable");

	Params::ActivityDetailsDisplay_C_SetButtonsInteractable Parms{};

	Parms.IsInteractionEnabled = IsInteractionEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.ResetWidgetState
// (Event, Protected, BlueprintEvent)

void UActivityDetailsDisplay_C::ResetWidgetState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "ResetWidgetState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.RefreshDisabledState
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UActivityDetailsDisplay_C::RefreshDisabledState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "RefreshDisabledState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.RefreshContentWarnings
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UActivityDetailsDisplay_C::RefreshContentWarnings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "RefreshContentWarnings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "PreConstruct");

	Params::ActivityDetailsDisplay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnPartySizeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             PartySize                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::OnPartySizeChanged(const int32 PartySize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnPartySizeChanged");

	Params::ActivityDetailsDisplay_C_OnPartySizeChanged Parms{};

	Parms.PartySize = PartySize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnParentActivated
// (Event, Protected, BlueprintEvent)

void UActivityDetailsDisplay_C::OnParentActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnParentActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnLocalPlayerPromotedToLeader
// (Event, Protected, BlueprintEvent)

void UActivityDetailsDisplay_C::OnLocalPlayerPromotedToLeader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnLocalPlayerPromotedToLeader");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnLocalPlayerDemoted
// (Event, Protected, BlueprintEvent)

void UActivityDetailsDisplay_C::OnLocalPlayerDemoted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnLocalPlayerDemoted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnIsFavoriteChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsFavorite                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const bool                              bPlayAnimation                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::OnIsFavoriteChanged(const bool bIsFavorite, const bool bPlayAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnIsFavoriteChanged");

	Params::ActivityDetailsDisplay_C_OnIsFavoriteChanged Parms{};

	Parms.bIsFavorite = bIsFavorite;
	Parms.bPlayAnimation = bPlayAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnDetailsUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsDetailsValid                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::OnDetailsUpdated(const bool bIsDetailsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnDetailsUpdated");

	Params::ActivityDetailsDisplay_C_OnDetailsUpdated Parms{};

	Parms.bIsDetailsValid = bIsDetailsValid;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.OnDescriptionScrollRestarted
// (Event, Protected, BlueprintEvent)

void UActivityDetailsDisplay_C::OnDescriptionScrollRestarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "OnDescriptionScrollRestarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.GetCreatorTextFormat
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      CreatorName                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UActivityDetailsDisplay_C::GetCreatorTextFormat(const class FText& CreatorName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "GetCreatorTextFormat");

	Params::ActivityDetailsDisplay_C_GetCreatorTextFormat Parms{};

	Parms.CreatorName = std::move(CreatorName);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.ExecuteUbergraph_ActivityDetailsDisplay
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityDetailsDisplay_C::ExecuteUbergraph_ActivityDetailsDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "ExecuteUbergraph_ActivityDetailsDisplay");

	Params::ActivityDetailsDisplay_C_ExecuteUbergraph_ActivityDetailsDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityDetailsDisplay.ActivityDetailsDisplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityDetailsDisplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityDetailsDisplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

