#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaStatsRow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaStatsRow.AthenaStatsRow_C
// 0x0008 (0x02B0 - 0x02A8)
class UAthenaStatsRow_C final : public UFortProfileStatsRow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_AthenaStatsRow(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetStatValueAsText(const class FText& StatValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaStatsRow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaStatsRow_C")
	}
	static class UAthenaStatsRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaStatsRow_C>();
	}
};
DUMPER7_ASSERTS_UAthenaStatsRow_C;

}

