#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_GrenadeCameraShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_GrenadeCameraShake.B_GrenadeCameraShake_C
// 0x0000 (0x01B0 - 0x01B0)
class UB_GrenadeCameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_GrenadeCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_GrenadeCameraShake_C")
	}
	static class UB_GrenadeCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_GrenadeCameraShake_C>();
	}
};
DUMPER7_ASSERTS_UB_GrenadeCameraShake_C;

}

