#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Melee_Impact_Pickaxe_Athena_Squeak

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "B_Athena_Pickaxe_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Melee_Impact_Pickaxe_Athena_Squeak.B_Melee_Impact_Pickaxe_Athena_Squeak_C
// 0x0008 (0x1570 - 0x1568)
class AB_Melee_Impact_Pickaxe_Athena_Squeak_C final : public AB_Athena_Pickaxe_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Melee_Impact_Pickaxe_Athena_Squeak_C; // 0x1568(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_B_Melee_Impact_Pickaxe_Athena_Squeak(int32 EntryPoint);
	void OnPlayImpactFX(const struct FHitResult& HitResult, EPhysicalSurface ImpactPhysicalSurface, class UFXSystemComponent* SpawnedPSC);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("B_Melee_Impact_Pickaxe_Athena_Squeak_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"B_Melee_Impact_Pickaxe_Athena_Squeak_C")
	}
	static class AB_Melee_Impact_Pickaxe_Athena_Squeak_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Melee_Impact_Pickaxe_Athena_Squeak_C>();
	}
};
DUMPER7_ASSERTS_AB_Melee_Impact_Pickaxe_Athena_Squeak_C;

}

