#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BacchusBoundActionButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BacchusBoundActionButton.BacchusBoundActionButton_C
// 0x0020 (0x0F20 - 0x0F00)
class UBacchusBoundActionButton_C final : public UBacchusBoundActionButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0F00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                ContentBorder;                                     // 0x0F08(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortMobileImage*                       FortMobileImageInputAction;                        // 0x0F10(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              InputActionIconScale;                              // 0x0F18(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_BacchusBoundActionButton(int32 EntryPoint);
	void OnUpdateInputAction();
	void UpdateInputActionIconSize();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BacchusBoundActionButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BacchusBoundActionButton_C")
	}
	static class UBacchusBoundActionButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBacchusBoundActionButton_C>();
	}
};
DUMPER7_ASSERTS_UBacchusBoundActionButton_C;

}

