#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CamShake_Athena_Player_PreSlide

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CamShake_Athena_Player_PreSlide.CamShake_Athena_Player_PreSlide_C
// 0x0000 (0x01B0 - 0x01B0)
class UCamShake_Athena_Player_PreSlide_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CamShake_Athena_Player_PreSlide_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CamShake_Athena_Player_PreSlide_C")
	}
	static class UCamShake_Athena_Player_PreSlide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCamShake_Athena_Player_PreSlide_C>();
	}
};
DUMPER7_ASSERTS_UCamShake_Athena_Player_PreSlide_C;

}

