#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CorruptionGameplayCodeUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function CorruptionGameplayCodeUI.FortPowerupReticleExtensionWidget.GetCurrentOverheatPercent
// 0x0004 (0x0004 - 0x0000)
struct FortPowerupReticleExtensionWidget_GetCurrentOverheatPercent final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FortPowerupReticleExtensionWidget_GetCurrentOverheatPercent;

// Function CorruptionGameplayCodeUI.FortPowerupReticleExtensionWidget.GetCurrentOverheatValue
// 0x0004 (0x0004 - 0x0000)
struct FortPowerupReticleExtensionWidget_GetCurrentOverheatValue final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FortPowerupReticleExtensionWidget_GetCurrentOverheatValue;

// Function CorruptionGameplayCodeUI.FortPowerupReticleExtensionWidget.GetOverheatingMaxValue
// 0x0004 (0x0004 - 0x0000)
struct FortPowerupReticleExtensionWidget_GetOverheatingMaxValue final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FortPowerupReticleExtensionWidget_GetOverheatingMaxValue;

}

