#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryOverrideMatchmakingUIComponent

#include "Basic.hpp"

#include "DiscoveryBrowserUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DiscoveryOverrideMatchmakingUIComponent.DiscoveryOverrideMatchmakingUIComponent_C
// 0x0000 (0x0100 - 0x0100)
class UDiscoveryOverrideMatchmakingUIComponent_C final : public UOverrideMatchmakingUIComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DiscoveryOverrideMatchmakingUIComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DiscoveryOverrideMatchmakingUIComponent_C")
	}
	static class UDiscoveryOverrideMatchmakingUIComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiscoveryOverrideMatchmakingUIComponent_C>();
	}
};
DUMPER7_ASSERTS_UDiscoveryOverrideMatchmakingUIComponent_C;

}

