#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortniteConversationRuntime

#include "Basic.hpp"


namespace SDK
{

// Enum FortniteConversationRuntime.EInteractionRange
// NumValues: 0x0003
enum class EInteractionRange : uint8
{
	Preview                                  = 0,
	Interaction                              = 1,
	EInteractionRange_MAX                    = 2,
};

// ScriptStruct FortniteConversationRuntime.FortConversationConditionalMessage
// 0x0020 (0x0020 - 0x0000)
struct FFortConversationConditionalMessage final
{
public:
	class UFortConversationContextCondition*      Condition;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, PersistentInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   Message;                                           // 0x0008(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FFortConversationConditionalMessage;

// ScriptStruct FortniteConversationRuntime.FortConversationNodeConditionalMessages
// 0x0010 (0x0010 - 0x0000)
struct FFortConversationNodeConditionalMessages final
{
public:
	TArray<struct FFortConversationConditionalMessage> Messages;                                     // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FFortConversationNodeConditionalMessages;

}

