#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontendBackgroundData

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct FrontendBackgroundData.FrontendBackgroundData
// 0x0078 (0x0078 - 0x0000)
struct FFrontendBackgroundData final
{
public:
	TSoftObjectPtr<class UTexture>                Texture_2_3547D6284A0E2943DB5EC88EE87E97DF;        // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInstance>       Material_6_CE9D2295415B51CDF1ED17B4FF554781;       // 0x0028(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInstance>       PreBlurMaterial_7_D600AA604396EA3D679C70876327DEF8; // 0x0050(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FFrontendBackgroundData;

}

