#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontendCamera_VaultRotator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FrontendCamera_VaultRotator.FrontendCamera_VaultRotator_C
// 0x0020 (0x0860 - 0x0840)
class AFrontendCamera_VaultRotator_C final : public AFortCameraBase
{
public:
	uint8                                         Pad_838[0x8];                                      // 0x0838(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0840(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCameraComponent*                       LoginCamera_0;                                     // 0x0848(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AVaultRotator_C*                        ActiveVaultRotator;                                // 0x0850(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetVaultRotatorLighting(class FName ItemRotatorTag);
	void OnDeactivated(class AFortPlayerController* PlayerController);
	void OnActivated(class AFortPlayerController* PlayerController);
	void ExecuteUbergraph_FrontendCamera_VaultRotator(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FrontendCamera_VaultRotator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FrontendCamera_VaultRotator_C")
	}
	static class AFrontendCamera_VaultRotator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontendCamera_VaultRotator_C>();
	}
};
DUMPER7_ASSERTS_AFrontendCamera_VaultRotator_C;

}

