#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_ImpactImmunity

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ImpactImmunity.GE_ImpactImmunity_C
// 0x0000 (0x0800 - 0x0800)
class UGE_ImpactImmunity_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_ImpactImmunity_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_ImpactImmunity_C")
	}
	static class UGE_ImpactImmunity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ImpactImmunity_C>();
	}
};
DUMPER7_ASSERTS_UGE_ImpactImmunity_C;

}

