#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionGen_Madman

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_Madman.MissionGen_Madman_C
// 0x0000 (0x07E0 - 0x07E0)
class UMissionGen_Madman_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionGen_Madman_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MissionGen_Madman_C")
	}
	static class UMissionGen_Madman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Madman_C>();
	}
};
DUMPER7_ASSERTS_UMissionGen_Madman_C;

}

