#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Pawn_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Enum_NPC_AlertLevel_structs.hpp"
#include "EnemyPawn_Parent_Deimos_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Struct_NPC_TargetSlots_structs.hpp"
#include "Enum_NPC_TargetSlots_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Pawn_Parent.NPC_Pawn_Parent_C
// 0x0710 (0x3250 - 0x2B40)
#pragma pack(push, 0x1)
class alignas(0x10) ANPC_Pawn_Parent_C : public AEnemyPawn_Parent_Deimos_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_NPC_Pawn_Parent_C;                  // 0x2B40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFortActorComponent_Affiliation*        FortActorComponent_Affiliation;                    // 0x2B48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundLibraryComponent*                 SoundLibrary_Component;                            // 0x2B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        MovementAudioComponent;                            // 0x2B58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNPC_VoiceComponent_C*                  NPC_VoiceComponent;                                // 0x2B60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        VOAudioComponent;                                  // 0x2B68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortWidgetComponent*                   NPCStatusWidget;                                   // 0x2B70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_ScaleMeshInOrOut_MeshScaleAlpha_9DAAC0B243D26E4160CEC3A458AE0E86; // 0x2B78(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_ScaleMeshInOrOut__Direction_9DAAC0B243D26E4160CEC3A458AE0E86; // 0x2B7C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B7D[0x3];                                     // 0x2B7D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_ScaleMeshInOrOut;                         // 0x2B80(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_NPC_RecentlyDamaged;                            // 0x2B88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_NPC_AlertLevel                           NPC_AlertLevel;                                    // 0x2B90(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	Enum_NPC_AlertLevel                           NPC_AlertLevelPrevious;                            // 0x2B91(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B92[0x6];                                     // 0x2B92(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<Enum_NPC_AlertLevel, struct FGameplayTag> NPC_AlertLevelToTagMap;                           // 0x2B98(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_StatusWidgetHealthBarDisabled;                 // 0x2BE8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BE9[0x3];                                     // 0x2BE9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           GameplayCue_PickupGrabbed;                         // 0x2BEC(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   NPC_BestLootRarityInInventory;                     // 0x2BF4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_DebugPawn;                                     // 0x2BF5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_ShowInventoryRarityVisuals;                    // 0x2BF6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BF7[0x1];                                     // 0x2BF7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         InventoryGlowDelay;                                // 0x2BF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BFC[0x4];                                     // 0x2BFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         NPC_NumberOfInventoryItemsToDeliverHF;             // 0x2C00(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_SpawnInvisible;                                // 0x2C28(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_ScaleMeshInOnSpawn;                            // 0x2C29(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C2A[0x6];                                     // 0x2C2A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  TC_NPC_SpawnAbilityTag;                            // 0x2C30(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  TC_NPC_AlternateSpawnAbilityTag;                   // 0x2C50(0x0020)(Edit, BlueprintVisible)
	bool                                          NPC_IsSpawning;                                    // 0x2C70(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C71[0x3];                                     // 0x2C71(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NPC_OriginalGravityScale;                          // 0x2C74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               NPC_OriginalRotationRate;                          // 0x2C78(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          NPC_HasPawnGoal;                                   // 0x2C84(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C85[0x3];                                     // 0x2C85(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 NPC_PawnGoalActor;                                 // 0x2C88(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_NumberOfInventoryItemsToConsumeBeforeFullHF;   // 0x2C90(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_PawnIsDestroyingBuildingForNavigation;         // 0x2CB8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CB9[0x7];                                     // 0x2CB9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         MaxIdleVODelay;                                    // 0x2CC0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         MinIdleVODelay;                                    // 0x2CE8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         NPC_DeathDropLootDelay;                            // 0x2D10(0x0028)(Edit, BlueprintVisible)
	class FName                                   NPC_DeathDropLootTierGroupName;                    // 0x2D38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  NPC_DeathDropLootRequiredDamageTags;               // 0x2D40(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  NPC_DeathDropLootForbiddenDamageTags;              // 0x2D60(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  GrantStartingItemsAbilityTC;                       // 0x2D80(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_HasItemInInventory;                            // 0x2DA0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DA1[0x3];                                     // 0x2DA1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           VoiceTag_FullAlertIdle;                            // 0x2DA4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_Idle;                                     // 0x2DAC(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_ReturnToIdle;                             // 0x2DB4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_LostTarget;                               // 0x2DBC(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_Suspicious;                               // 0x2DC4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_FullAlert;                                // 0x2DCC(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DD4[0x4];                                     // 0x2DD4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStruct_NPC_TargetSlots>        NPC_TargetSlotsHF;                                 // 0x2DD8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_DamageCanCancelIntroPhase;                     // 0x2DE8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DE9[0x7];                                     // 0x2DE9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagQuery                      TQ_NPC_DamageTagsThatCanCancelIntroPhase;          // 0x2DF0(0x0048)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 GE_NPC_IntroPhaseBehaviorCooldown;                 // 0x2E38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_IntroBehaviorActive;                            // 0x2E40(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Debug_NPC_AlertLevelForced;                        // 0x2E60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E61[0x7];                                     // 0x2E61(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         SoundLibs;                                         // 0x2E68(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_PawnCanInteractInternal;                       // 0x2E78(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E79[0x7];                                     // 0x2E79(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         NPC_PrimtiveDataFloatSetRandomlyInRange;           // 0x2E80(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatIndexHF;                      // 0x2EA8(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatMinRangeHF;                   // 0x2ED0(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatMaxRangeHF;                   // 0x2EF8(0x0028)(Edit, BlueprintVisible)
	class AActor*                                 NPC_Leader;                                        // 0x2F20(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCue_LeaderSet;                             // 0x2F28(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                         SoundLibs_Alert;                                   // 0x2F30(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UClass*>                         SoundLibs_Aggressive;                              // 0x2F40(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UClass*>                         SoundLibs_Foley;                                   // 0x2F50(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundBase*                             UnawareStateChangeSound;                           // 0x2F60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             AlertStateChangeSound;                             // 0x2F68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             AggressiveStateChangeSound;                        // 0x2F70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         NPC_Skeletal_Mesh_Index;                           // 0x2F78(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F7C[0x4];                                     // 0x2F7C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             TamedSound;                                        // 0x2F80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        StateChangeSound;                                  // 0x2F88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                         SoundLibs_Foley_Water;                             // 0x2F90(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 CurrentFoleyLib;                                   // 0x2FA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CurrentSoundLIb;                                   // 0x2FA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_ShouldDespawnFromStormHF;                      // 0x2FB0(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_DespawnTimerHF;                                // 0x2FD8(0x0028)(Edit, BlueprintVisible)
	struct FGameplayTag                           NPC_DespawnGameplayTag;                            // 0x3000(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           NPC_TestIsInSafeZoneTimer;                         // 0x3008(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           NPC_DespawnFromStormTimer;                         // 0x3010(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_isTryingToDespawn;                             // 0x3018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3019[0x3];                                     // 0x3019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           NPC_ResetIntroGameplayTags;                        // 0x301C(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	float                                         SelectedPrimitiveDataFloat;                        // 0x3024(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCue_Death;                                 // 0x3028(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*>             OG_Materials;                                      // 0x3030(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_Apply_GE_for_Swimming;                         // 0x3040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3041[0x7];                                     // 0x3041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 NPC_GE_ClassToApplyForSwimming;                    // 0x3048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Exit_Burst_GC;                                     // 0x3050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3051[0x3];                                     // 0x3051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            NPC_GE_AppliedForSwimming;                         // 0x3054(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	class FName                                   GoalActorBBKey;                                    // 0x305C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCueLureInterest;                           // 0x3064(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_306C[0x4];                                     // 0x306C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                NPC_PreviousLureGoal;                              // 0x3070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Exit_Water;                                        // 0x3078(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Enter_Water;                                       // 0x3080(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_MaxDistanceFromDamagedNPCToDrawHeallthBarHF;   // 0x3088(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_HealthBarHideTimeAfterDeathHF;                 // 0x30B0(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PlayEffectWhenLuredHF;                         // 0x30D8(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PawnCanInteractHF;                             // 0x3100(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowInteractOnlyWhenUnawareHF;                // 0x3128(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowInteractWhenHasLeaderHF;                  // 0x3150(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowDrownInShallowWaterHF;                    // 0x3178(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_IsInventoryInitialized;                        // 0x31A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isGCForLeaderSetLooping;                           // 0x31A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31A2[0x2];                                     // 0x31A2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           NPC_DeathByStormTag;                               // 0x31A4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_TryDespawnAbility;                             // 0x31AC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31AD[0x3];                                     // 0x31AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            GeOutsideSafeZoneDamageHandle;                     // 0x31B0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsGEStormDamageInit;                               // 0x31B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_MeshScalingInProgress;                         // 0x31B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_DisableCapsuleOverlapsWhenScalingOut;          // 0x31BA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31BB[0x1];                                     // 0x31BB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                NPC_OriginalMeshScale;                             // 0x31BC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              NPCScaleMeshInCompleted;                           // 0x31C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              NPCScaleMeshOutCompleted;                          // 0x31D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          NPC_CanDropLoot;                                   // 0x31E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31E9[0x7];                                     // 0x31E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         NPC_StaleDespawnTestDistance_HF;                   // 0x31F0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         NPC_StaleDespawnTimeThreshold_HF;                  // 0x3218(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         NPC_LastNonStaleCheckTime;                         // 0x3240(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCanBeDamagedByNullInstigator;                     // 0x3244(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnteringWater;                                   // 0x3245(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddSoundSystemLibraries();
	void BeginMusicTracker();
	void CheckSoundLibraryAdded(TArray<class UClass*>& Libraries);
	void CheckSoundLibraryRemoved(TArray<class UClass*>& Libraries);
	void Debug_AlertLevel_ClearDebug();
	void Debug_AlertLevel_ForceLevel(Enum_NPC_AlertLevel NewNPC_AlertLevel);
	void Debug_ForceAlertLevel_Aggressive();
	void Debug_ForceAlertLevel_Alerted();
	void Debug_ForceAlertLevel_Invalid();
	void Debug_ForceAlertLevel_NA();
	void Debug_ForceAlertLevel_Unaware();
	void DespawnDueToStorm();
	void End_Music_Tracker();
	void ExecuteUbergraph_NPC_Pawn_Parent(int32 EntryPoint);
	void GetSoundFoleyLibrary();
	void GrantStartingItems();
	void HandleInteracts();
	void InitializeInventory();
	void InitializeTestInSafeZone();
	void LuredInterest();
	void LuredOnServer(Enum_NPC_AlertLevel AlertLevel);
	void NPC_AlertLevelChangedServer(Enum_NPC_AlertLevel NPCAlertLevel);
	void NPC_ApplyGameplayEffectWithMMRScaling(class AActor* Actor, class UClass* GE_Class);
	void NPC_ApplyRecentlyDamagedTag(class UClass* RecentlyDamagedOverride);
	void NPC_AttemptToSetLeader(class AActor* PossibleLeader);
	void NPC_CanBeInteractedWith(bool* CanInteract);
	void NPC_CheckForDespawnIfStaleToPlayers(class AFortPlayerPawn* ClosestFortPlayerPawn);
	void NPC_CheckIsInSafeZone(bool* TestSucceeded, bool* IsInSafeZone);
	void NPC_ClearOutTargetSlots();
	void NPC_DamageAttemptDisableIntroPhaseBehavior(const struct FGameplayTagContainer& DamageTags);
	void NPC_DisableIntroPhaseBehavior();
	void NPC_GetAlertLevelInfo(Enum_NPC_AlertLevel* AlertLevel, struct FGameplayTag* AlertLevelTag, bool* ValidDataFound);
	void NPC_GetInventoryInformation(bool* HasItemInInventory, int32* TotalNumberOfInventoryItems, int32* LastInventoryItemIndex, bool* HasEnoughItemsToDeliver, bool* ConsumedEnoughItemsToBeConsideredFull);
	void NPC_GetSafeZonePhase(int32* SafeZonePhase);
	void NPC_GetScalableFloatHotfixValue(const struct FScalableFloat& ScalableFloatHotfix, float AtLevel, bool* AsBool, int32* AsIntRounded, float* AsFloat);
	void NPC_HandleAlertLevelVoice();
	void NPC_HasLeader_(bool* HasLeader_, class AActor** Leader);
	void NPC_InitializeIdleVO();
	void NPC_LeaderSet(bool Success_, class AActor* Leader);
	void NPC_MulticastGameplayCueDeath();
	void NPC_ParentLaunchVehicle(class AActor* Vehicle, const struct FVector& Velocity);
	void NPC_Pawn_Interact(class AFortAIPawn* AI, class AFortPlayerController* InteractingPlayerController, EInteractionBeingAttempted InteractionBeingAttempted);
	void NPC_PawnDebugMessage(const class FString& String, bool OnlyWhenDebug);
	void NPC_PickupDropped(class AFortPickup* FortPickupDropped);
	void NPC_PickupGrabbed(class AFortPickup* FortPickupGrabbed);
	void NPC_PickupGrabbed_Destroyed(class AActor* ActorGrabbed);
	void NPC_ResetOriginalGravityScale();
	void NPC_ResetOriginalRotationRate();
	void NPC_ScalableFloatIsValid(const struct FScalableFloat& ScalableFloat, bool* Valid);
	void NPC_SendGameplayCuePickupGrabbed();
	void NPC_SetBestLootRarityInInventory(EFortRarity* NPC_BestLootRarityInInventory_0);
	void NPC_SetCanDropLoot(bool CanDropLoot);
	void NPC_SetLeader(class AActor* Leader, bool* Success_, class AActor** LeaderSet);
	void NPC_SetLootCollectionPhaseCompleteToBlackboard(bool LootCollectionPhaseComplete);
	void NPC_SetReturnGatheredLootToBlackboard();
	void NPC_SetupHealthBarOnDeath();
	void NPC_TargetSlotInfo(Enum_NPC_TargetSlots TargetSlotType, class AActor* TargetWeWantToSlotOnto, int32* TargetSlotCount, int32* TargetSlotMax, int32* NPC_TargetSlotsRequired, bool* TargetSlotsMaxOrMore, bool* TargetSlotCountIsExactlyMax, bool* NPC_IsTargetSlotOwner, bool* NPC_HasSpaceToSlotOnTarget, Enum_NPC_TargetSlots* TargetSlotTypeOut, class UClass** TargetSlotCountingGE, struct FScalableFloat* AI_TargetSlotSizeHF, struct FScalableFloat* AI_TargetSlotDurationHF, class UClass** TargetSlotOverrideGE, class UClass** TargetSlotOwnerGE, class UClass** TargetSlotCountingMaxedGE);
	void NPC_TargetSlotIsUsingOverride(Enum_NPC_TargetSlots TargetSlotType, class AActor* TargetWeWantToSlotOnto, bool* Override);
	void NPC_TryToDropLootOnDeath(const struct FGameplayTagContainer& DamageTags, bool* CanDropLoot);
	void NPC_UpdateInteract(bool CanInteract, bool* EnabledInteract);
	void NPCAlertLevelChangedClient(Enum_NPC_AlertLevel NPC_AlertLevel_0);
	void NPCDisableHealthBars();
	void NPCEnableHealthBars();
	void NPCScaleMeshIn();
	void NPCScaleMeshOut();
	void On_NPC_PawnInteractedWith(class AActor* AIPawn, class AFortPlayerPawn* InteractingPlayerPawn);
	void OnBeginDeepWaterInteraction(const struct FVector& WaterSurfaceLocation, float WaterDepth);
	void OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnEnteredWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsFirstBody);
	void OnExitedWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsLastBody);
	void OnPawnHealthChanged_Event_0();
	void OnRep_NPC_BestLootRarityInInventory();
	void OnRep_NPC_Leader();
	void OnRep_NPC_AlertLevel();
	void OnRep_SelectedPrimitiveDataFloat();
	void Play_Water_Splash_at_Water_Surface(class AFortWaterBodyActor* Water_Body, bool Enter_Water_0);
	void PlayEnterWaterSplash(class AFortWaterBodyActor* Water_Body);
	void PlayExitWaterSplash(class AFortWaterBodyActor* Water_Body);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceivePossessed(class AController* NewController);
	void RemoveSoundSystemLibraries();
	void RequestUpdateNPCAlertLevel(Enum_NPC_AlertLevel NPC_AlertLevel_0);
	void ResetMaterialFromDeath();
	void SelectPrimitiveDataFloat();
	void SetPrimitiveDataFloat();
	bool ShouldUpdateSkeletalMesh();
	void StartUpdatingHleathBarWidget();
	void StopTestingIsInSafeZone();
	void StopUpdatingHealthBarWidget();
	void StoreOriginalGravityAndRotation();
	void TestIsInSafeZone();
	void TestLoot();
	void Timeline_ScaleMeshInOrOut__FinishedFunc();
	void Timeline_ScaleMeshInOrOut__UpdateFunc();
	void TriggerDespawnAbility();
	void TriggerIdleVO();
	void TryToDespawnDueToStorm(bool Reset_Timer);
	void TryWaterInteractionDrown();
	void UpdateSoundLibFoley();
	void UpdateSoundLibrary(Enum_NPC_AlertLevel Alert_Level);
	void WidgetVisibilityChanged(bool bVisible);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_Pawn_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_Pawn_Parent_C")
	}
	static class ANPC_Pawn_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Pawn_Parent_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ANPC_Pawn_Parent_C;

}

