#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerSurveyWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerSurveyWidget.PlayerSurveyWidget_C
// 0x0000 (0x0528 - 0x0528)
class UPlayerSurveyWidget_C final : public UFortPlayerSurveyWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerSurveyWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerSurveyWidget_C")
	}
	static class UPlayerSurveyWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerSurveyWidget_C>();
	}
};
DUMPER7_ASSERTS_UPlayerSurveyWidget_C;

}

