#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarProfile

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarProfile.SidebarProfile_C
// 0x0008 (0x03D8 - 0x03D0)
class USidebarProfile_C final : public UFortSocialProfilePanel
{
public:
	class USidebarProfileSubPanelFriendRequest_C* SubPanelFriendRequest;                             // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SidebarProfile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SidebarProfile_C")
	}
	static class USidebarProfile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarProfile_C>();
	}
};
DUMPER7_ASSERTS_USidebarProfile_C;

}

