#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SquadSelection

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SquadSelection.SquadSelection_C
// 0x0018 (0x03C8 - 0x03B0)
class USquadSelection_C final : public UFortSquadSelectionMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCloseButton_C*                         Mobile_CloseButton;                                // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_0;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__CloseButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button);
	void ExecuteUbergraph_SquadSelection(int32 EntryPoint);
	void OnLocalPlayerParticipationChanged(bool bIsParticipating);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SquadSelection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SquadSelection_C")
	}
	static class USquadSelection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USquadSelection_C>();
	}
};
DUMPER7_ASSERTS_USquadSelection_C;

}

