#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StreamingRadio

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class StreamingRadio.StreamingRadioManagerNative
// 0x0010 (0x0230 - 0x0220)
class AStreamingRadioManagerNative final : public AActor
{
public:
	class UFortStreamMediaSource*                 StreamMediaSource;                                 // 0x0220(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMediaPlayer*                           MediaPlayer;                                       // 0x0228(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StreamingRadioManagerNative")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StreamingRadioManagerNative")
	}
	static class AStreamingRadioManagerNative* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStreamingRadioManagerNative>();
	}
};
DUMPER7_ASSERTS_AStreamingRadioManagerNative;

}

