#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterMaterialInteractHandler

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WaterMaterialInteractHandler.WaterMaterialInteractHandler_C
// 0x0000 (0x00A8 - 0x00A8)
class UWaterMaterialInteractHandler_C final : public UFortCurieElementInteractWithMaterialHandlerWater
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterMaterialInteractHandler_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WaterMaterialInteractHandler_C")
	}
	static class UWaterMaterialInteractHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWaterMaterialInteractHandler_C>();
	}
};
DUMPER7_ASSERTS_UWaterMaterialInteractHandler_C;

}

